import { uaLong } from './ua.long';

export const deLong: Record<string, string> = {
	...Object.fromEntries(Object.keys(uaLong).map((sourceText) => [sourceText, sourceText])),
	'This route does not match any practice entry. Use the homepage to pick a valid profile.':
		'Diese Route entspricht keinem Praktikumseintrag. Verwenden Sie die Startseite, um ein gültiges Profil auszuwählen.',
	'Each service page is driven from a consistent structure so teams can evaluate scope, execution model, support expectations, and delivery constraints before starting.':
		'Jede Serviceseite folgt einer einheitlichen Struktur, damit Teams Umfang, Umsetzungsmodell, Support-Erwartungen und Liefergrenzen vor dem Start bewerten können.',
	'Clear scope, visible execution, and production-ready outcomes':
		'Klarer Umfang, transparente Umsetzung und produktionsreife Ergebnisse',
	'Founders, product teams, and companies with real delivery needs':
		'Für Gründer, Produktteams und Unternehmen mit realem Umsetzungsbedarf',
	'Everything on this page is generated from the service data itself':
		'Alles auf dieser Seite wird direkt aus den Servicedaten erzeugt',
	'That gives you a stable content model for future expansion: landing summaries, dedicated service pages, navigation, structured sections, and related-offer linking all stay synchronized.':
		'Das gibt Ihnen ein stabiles Inhaltsmodell für die weitere Skalierung: Landing-Zusammenfassungen, eigene Serviceseiten, Navigation, strukturierte Abschnitte und Verknüpfungen zu verwandten Angeboten bleiben synchron.',
	'This route does not match any configured service. Return to the homepage and open one of the available service entries.':
		'Diese Route entspricht keinem konfigurierten Service. Kehren Sie zur Startseite zurück und öffnen Sie einen der verfügbaren Serviceeinträge.',
	'Web freelancer\'s community based in Ukraine with over 10 years in app and web development. Working to create products with the "Waw!" aftertaste.':
		'Eine in der Ukraine ansässige Community von Web-Freelancern mit über 10 Jahren Erfahrung in App- und Webentwicklung. Wir arbeiten daran, Produkte mit einem echten "Wow!"-Effekt zu schaffen.',
	'Tailored digital products delivered with modern frameworks and clean engineering.':
		'Maßgeschneiderte digitale Produkte, umgesetzt mit modernen Frameworks und sauberer Engineering-Praxis.',
	'Remote-first collaboration for founders, teams, and growing companies worldwide.':
		'Remote-First-Zusammenarbeit für Gründer, Teams und wachsende Unternehmen weltweit.',
	'Short feedback loops, pragmatic delivery, and production-ready implementation.':
		'Kurze Feedbackschleifen, pragmatische Umsetzung und produktionsreife Implementierung.',
	'Comprehensive digital delivery across product, engineering, design, operations, and growth support.':
		'Umfassende digitale Umsetzung über Produkt, Engineering, Design, Operations und Wachstumsunterstützung hinweg.',
	'Need something specific? We also shape custom delivery models for unique product or business constraints.':
		'Brauchen Sie etwas Spezifisches? Wir gestalten auch individuelle Umsetzungsmodelle für besondere Produkt- oder Geschäftsanforderungen.',
	'We use current frameworks, proven infrastructure, and pragmatic tooling to ship faster without sacrificing maintainability.':
		'Wir nutzen aktuelle Frameworks, bewährte Infrastruktur und pragmatische Tools, um schneller zu liefern, ohne die Wartbarkeit zu opfern.',
	'We choose modern tools when they materially improve delivery, quality, or leverage.':
		'Wir wählen moderne Tools dann, wenn sie Lieferung, Qualität oder Effizienz spürbar verbessern.',
	'Every decision is shaped around growth, maintainability, and pragmatic future changes.':
		'Jede Entscheidung ist auf Wachstum, Wartbarkeit und pragmatische Weiterentwicklung ausgerichtet.',
	'Secure defaults are part of the delivery process, not a patch layered on later.':
		'Sichere Standards sind Teil des Lieferprozesses und kein nachträglich aufgesetzter Zusatz.',
	'A clear sequence from discovery through support, tuned for lean collaboration and production-ready outcomes.':
		'Eine klare Abfolge von Discovery bis Support, abgestimmt auf schlanke Zusammenarbeit und produktionsreife Ergebnisse.',
	'We align on the business context, constraints, desired outcome, and success signals.':
		'Wir stimmen uns über Geschäftskontext, Einschränkungen, gewünschte Ergebnisse und Erfolgssignale ab.',
	'Scope is turned into a practical roadmap with delivery stages and technical options.':
		'Der Umfang wird in eine praktikable Roadmap mit Lieferphasen und technischen Optionen überführt.',
	'Implementation runs in short iterations with visible progress and constant review.':
		'Die Umsetzung erfolgt in kurzen Iterationen mit sichtbarem Fortschritt und laufender Überprüfung.',
	'We verify product behavior, edge cases, and readiness before shipping to users.':
		'Wir prüfen Produktverhalten, Randfälle und Einsatzbereitschaft, bevor an Nutzer ausgeliefert wird.',
	'Release is handled with environment checks, monitoring, and rollback awareness.':
		'Der Release wird mit Umgebungsprüfungen, Monitoring und Rückfallstrategie abgesichert.',
	'After launch we keep refining performance, adding features, and maintaining stability.':
		'Nach dem Launch verbessern wir weiter die Performance, ergänzen Funktionen und sichern die Stabilität.',
	'Ready to transform your ideas into reality? Our team is here to help you navigate your digital journey.':
		'Bereit, Ihre Ideen in die Realität umzusetzen? Unser Team hilft Ihnen dabei, Ihren digitalen Weg sicher zu gestalten.',
	'Ohiyenka Street, 63, Kamianets-Podilskyi, Khmelnytskyi Region, 32301':
		'Ohijenkastraße 63, Kamjanez-Podilskyj, Region Chmelnyzkyj, 32301',
	'Tell us about your project requirements, timeline, and goals...':
		'Erzählen Sie uns von Ihren Projektanforderungen, Ihrem Zeitplan und Ihren Zielen...',
	'Weaving digital solutions that connect, capture, and deliver results. Your trusted partner for comprehensive IT services.':
		'Wir verweben digitale Lösungen, die verbinden, Aufmerksamkeit schaffen und Ergebnisse liefern. Ihr verlässlicher Partner für umfassende IT-Services.',
	'Explore the brand story, the digital work we delivered, and the live channels available for direct contact.':
		'Entdecken Sie die Markengeschichte, die von uns gelieferte digitale Arbeit und die aktiven Kanäle für den direkten Kontakt.',
	'This route does not match any configured partner. Return to the homepage and open one of the available profiles.':
		'Diese Route entspricht keinem konfigurierten Partner. Kehren Sie zur Startseite zurück und öffnen Sie eines der verfügbaren Profile.',
	'Demchuk Denys is a premium custom kitchen and furniture workshop. We specialize in creating tailored furniture solutions for your home: kitchens, wardrobes, walk-in closets, dressers, and furniture for living rooms and bedrooms. We provide precise measurements, develop a unique design project, manufacture with quality materials, and ensure professional installation. We work in Kamianets-Podilskyi and across Ukraine. By ordering from us, you get more than furniture — you get style, comfort, and top-level service.':
		'Demchuk Denys ist eine Premium-Werkstatt für maßgefertigte Küchen und Möbel. Wir sind auf individuelle Möbellösungen für Ihr Zuhause spezialisiert: Küchen, Kleiderschränke, Ankleiden, Kommoden sowie Möbel für Wohn- und Schlafzimmer. Wir übernehmen exakte Aufmaße, entwickeln ein individuelles Designprojekt, fertigen mit hochwertigen Materialien und sorgen für professionelle Montage. Wir arbeiten in Kamjanez-Podilskyj und in ganz Ukraine. Wenn Sie bei uns bestellen, erhalten Sie mehr als Möbel – Sie bekommen Stil, Komfort und Service auf höchstem Niveau.',
	'Web Art Work is the technology partner of Demchuk Denys workshop. We are responsible for creating a modern website, setting up a CRM system for order processing and workflow automation, and supporting marketing through social media promotion, SEO optimization, and branding. Our goal is the client business digital transformation for sales growth and better service.':
		'Web Art Work ist der Technologiepartner der Werkstatt Demchuk Denys. Wir sind für die Entwicklung einer modernen Website, die Einrichtung eines CRM-Systems für Auftragsbearbeitung und Workflow-Automatisierung sowie für die Marketingunterstützung über Social-Media-Promotion, SEO-Optimierung und Branding verantwortlich. Unser Ziel ist die digitale Transformation des Kundengeschäfts für mehr Umsatz und besseren Service.',
	'Silver Virgi creates custom stretch ceilings for modern interiors. We manufacture and install stretch ceilings of any complexity: classic, multi-level, and illuminated. We offer tailored solutions for apartments, private houses, offices, and commercial spaces. We guarantee precise measurements, material selection, visualization, professional installation, and long-lasting results. Silver Virgi stands for aesthetics, quality, and reliability that stay with you for years.':
		'Silver Virgi fertigt maßgeschneiderte Spanndecken für moderne Innenräume. Wir produzieren und montieren Spanndecken jeder Komplexität: klassisch, mehrstufig und beleuchtet. Wir bieten individuelle Lösungen für Wohnungen, Privathäuser, Büros und Gewerbeflächen. Wir garantieren exakte Aufmaße, Materialauswahl, Visualisierung, professionelle Montage und langlebige Ergebnisse. Silver Virgi steht für Ästhetik, Qualität und Zuverlässigkeit, die Sie über Jahre begleiten.',
	'Web Art Work is the technology partner of Silver Virgi. We built an effective website for the company that manufactures and installs stretch ceilings, aimed at different market segments from private clients to interior designers and developers. The site presents a wide range of solutions, examples of completed projects, and collaboration benefits while keeping ordering and communication convenient. We integrated a CRM system, automated leads, and support the business in marketing through SEO, advertising, and social media strategy. Our goal is to help Silver Virgi scale and become a leader in modern ceiling solutions.':
		'Web Art Work ist der Technologiepartner von Silver Virgi. Wir haben eine effektive Website für das Unternehmen entwickelt, das Spanndecken herstellt und montiert, ausgerichtet auf verschiedene Marktsegmente – von Privatkunden bis zu Innenarchitekten und Bauträgern. Die Website präsentiert ein breites Spektrum an Lösungen, Beispiele realisierter Projekte und die Vorteile einer Zusammenarbeit, während Bestellung und Kommunikation bequem bleiben. Wir haben ein CRM-System integriert, Leads automatisiert und unterstützen das Unternehmen im Marketing durch SEO, Werbung und Social-Media-Strategie. Unser Ziel ist es, Silver Virgi beim Skalieren zu helfen und zu einem führenden Anbieter moderner Deckensysteme zu machen.',
	'Panianka is a space for bridal fashion, fabrics, and accessories created for people who value style, aesthetics, and individuality. We offer refined wedding dresses that highlight life special moments, along with a large selection of lace, fabrics, and decorative accessories for creating unique garments, accessories, and original pieces. We work with brides, designers, and sewing professionals across Ukraine. Here you will find more than materials or a dress — you will find inspiration, professionalism, and impeccable service.':
		'Panianka ist ein Raum für Brautmode, Stoffe und Accessoires, geschaffen für Menschen, die Stil, Ästhetik und Individualität schätzen. Wir bieten elegante Brautkleider, die die besonderen Momente des Lebens unterstreichen, sowie eine große Auswahl an Spitze, Stoffen und dekorativen Accessoires zur Herstellung einzigartiger Kleider, Accessoires und Einzelstücke. Wir arbeiten mit Bräuten, Designern und Nähprofis in ganz Ukraine. Hier finden Sie mehr als Materialien oder ein Kleid – Sie finden Inspiration, Professionalität und makellosen Service.',
	'Web Art Work is the technology partner of the bridal fashion boutique. We delivered a full website with a product catalog, integrated a CRM system for smooth client work, and automated order accounting and processing. In addition, we support the business marketing side through advertising setup, SMM strategy, SEO optimization, and visual branding. Our goal is to strengthen the brand digitally while combining aesthetics, functionality, and profitability.':
		'Web Art Work ist der Technologiepartner der Brautmode-Boutique. Wir haben eine vollständige Website mit Produktkatalog geliefert, ein CRM-System für reibungslose Kundenarbeit integriert und die Erfassung sowie Verarbeitung von Bestellungen automatisiert. Zusätzlich unterstützen wir das Unternehmen im Marketing durch Werbeeinrichtung, SMM-Strategie, SEO-Optimierung und visuelles Branding. Unser Ziel ist es, die Marke digital zu stärken und dabei Ästhetik, Funktionalität und Wirtschaftlichkeit zu verbinden.',
	'Tpotier is a studio of bridal and couture textiles for designers, ateliers, and brides who value sophistication, individuality, and high craftsmanship. We offer carefully selected fabrics, delicate lace, and elegant decorative accessories for creating wedding dresses, accessories, and unique designer clothing. Our collection combines classic European aesthetics with modern trends to meet international market expectations. We work with designers, workshops, and brides from around the world, providing inspiration, quality, and professional support at every stage.':
		'Tpotier ist ein Studio für Braut- und Couture-Textilien für Designer, Ateliers und Bräute, die Raffinesse, Individualität und hohe Handwerkskunst schätzen. Wir bieten sorgfältig ausgewählte Stoffe, feine Spitze und elegante dekorative Accessoires für die Herstellung von Brautkleidern, Accessoires und einzigartiger Designermode. Unsere Kollektion verbindet klassische europäische Ästhetik mit modernen Trends, um den Erwartungen des internationalen Marktes zu entsprechen. Wir arbeiten mit Designern, Werkstätten und Bräuten aus aller Welt und bieten in jeder Phase Inspiration, Qualität und professionelle Unterstützung.',
	'Web Art Work is the technology partner of Tpotier. We created a modern website aimed at the international market, with a multilingual product catalog adapted to the needs of designers, ateliers, and brides from around the world. We integrated a CRM system for convenient order handling and client communication, and automated business processes for efficient management. We also support the project in marketing through visual style development, SEO optimization, targeted advertising, and social media presence strategy. Our goal is to scale the Tpotier brand through digital tools that support quality, image, and sales.':
		'Web Art Work ist der Technologiepartner von Tpotier. Wir haben eine moderne Website für den internationalen Markt entwickelt, mit einem mehrsprachigen Produktkatalog, der auf die Bedürfnisse von Designern, Ateliers und Bräuten aus aller Welt zugeschnitten ist. Wir haben ein CRM-System für komfortable Auftragsabwicklung und Kundenkommunikation integriert und Geschäftsprozesse für ein effizientes Management automatisiert. Zusätzlich unterstützen wir das Projekt im Marketing durch die Entwicklung eines visuellen Stils, SEO-Optimierung, zielgerichtete Werbung und eine Strategie für die Präsenz in sozialen Medien. Unser Ziel ist es, die Marke Tpotier mit digitalen Werkzeugen zu skalieren, die Qualität, Image und Verkauf unterstützen.',
	'VR Arena is a space for virtual entertainment for children, teenagers, and adults. Here you can immerse yourself in virtual reality using modern VR headsets and controllers. Shooters, adventures, racing, quests, and horrors are available for one or several players. We welcome individual visitors, groups of friends, and families. We explain, help, and guide you, so it works even for beginners. VR Arena is about new emotions, active leisure, and a memorable technology experience.':
		'VR Arena ist ein Raum für virtuelle Unterhaltung für Kinder, Jugendliche und Erwachsene. Hier können Sie mit modernen VR-Headsets und Controllern in die virtuelle Realität eintauchen. Shooter, Abenteuer, Rennspiele, Quests und Horrorspiele stehen für einen oder mehrere Spieler zur Verfügung. Wir begrüßen Einzelbesucher, Freundesgruppen und Familien. Wir erklären, helfen und begleiten, sodass es auch für Einsteiger funktioniert. Bei VR Arena geht es um neue Emotionen, aktive Freizeit und ein unvergessliches Technologieerlebnis.',
	'Web Art Work is the technology partner of VR Arena. We built a website for the virtual reality venue that combines entertainment, technology, and convenient booking for gaming sessions. The site is aimed at individual visitors, groups of friends, families, and event organizers, from birthdays to corporate events. It presents the game catalog, visit conditions, event photos, and booking options. We integrated a CRM system for order handling, automated processes, launched advertising campaigns, and developed a digital strategy. Our goal is to help VR Arena scale, broaden its audience, and become a leading player in the virtual entertainment market.':
		'Web Art Work ist der Technologiepartner von VR Arena. Wir haben eine Website für die Virtual-Reality-Location entwickelt, die Unterhaltung, Technologie und eine bequeme Buchung von Spielsessions verbindet. Die Seite richtet sich an Einzelbesucher, Freundesgruppen, Familien und Veranstalter – von Geburtstagen bis zu Firmenevents. Sie präsentiert den Spielekatalog, Besuchsbedingungen, Veranstaltungsfotos und Buchungsoptionen. Wir haben ein CRM-System für die Auftragsbearbeitung integriert, Prozesse automatisiert, Werbekampagnen gestartet und eine digitale Strategie entwickelt. Unser Ziel ist es, VR Arena beim Skalieren zu unterstützen, die Zielgruppe zu erweitern und zu einem führenden Anbieter im Markt für virtuelle Unterhaltung zu machen.',
	'Jack Hoker is a leather goods workshop with more than 20 years of experience. We create bags, wallets, belts, backpacks, and accessories from genuine leather, combining handcrafted tradition with contemporary design. Every product carries the quality of trusted materials, attention to detail, and a distinctive style. We make items that last for years and gain even more character over time. We work for people who value functionality, authenticity, and craftsmanship proven by time.':
		'Jack Hoker ist eine Lederwarenwerkstatt mit mehr als 20 Jahren Erfahrung. Wir fertigen Taschen, Geldbörsen, Gürtel, Rucksäcke und Accessoires aus echtem Leder und verbinden traditionelle Handarbeit mit zeitgemäßem Design. Jedes Produkt steht für die Qualität bewährter Materialien, Liebe zum Detail und einen unverwechselbaren Stil. Wir schaffen Dinge, die jahrelang halten und mit der Zeit noch mehr Charakter gewinnen. Wir arbeiten für Menschen, die Funktionalität, Authentizität und über Jahre bewiesene Handwerkskunst schätzen.',
	'Web Art Work is the technology partner of Jack Hoker. We created a modern website for the leather goods brand that combines handcrafted authenticity with a relevant digital experience. The interface is adapted for clients who value quality, craftsmanship, and concise style. We implemented an online ordering system optimized for convenient communication and request processing, and connected a CRM for effective order management. We promote the brand through SEO, visual strategy, targeted advertising, and social media content. Our goal is to expand the Jack Hoker audience and strengthen the brand image built around the value of time, tradition, and quality.':
		'Web Art Work ist der Technologiepartner von Jack Hoker. Wir haben eine moderne Website für die Lederwarenmarke entwickelt, die handwerkliche Authentizität mit einem zeitgemäßen digitalen Erlebnis verbindet. Die Benutzeroberfläche ist auf Kunden zugeschnitten, die Qualität, Handwerkskunst und einen klaren Stil schätzen. Wir haben ein Online-Bestellsystem umgesetzt, das auf komfortable Kommunikation und effiziente Bearbeitung von Anfragen optimiert ist, und ein CRM für ein wirksames Auftragsmanagement angebunden. Wir fördern die Marke durch SEO, visuelle Strategie, zielgerichtete Werbung und Social-Media-Inhalte. Unser Ziel ist es, die Zielgruppe von Jack Hoker zu erweitern und das Markenbild rund um Zeit, Tradition und Qualität zu stärken.',
	'PORTIER CAKE is a premium cake, dessert, and candy-bar studio. We specialize in creating refined sweets from natural ingredients: wedding cakes, custom desserts, and festive candy bars. We work with individual wishes, choose stylish presentation, and care about the flawless taste of every product. We prepare everything with love and attention to detail in Kamianets-Podilskyi. When you order from us, you get more than a dessert — you get emotion, aesthetics, and sweet pleasure at the highest level.':
		'PORTIER CAKE ist ein Premium-Studio für Torten, Desserts und Candy Bars. Wir sind auf die Herstellung feiner Süßwaren aus natürlichen Zutaten spezialisiert: Hochzeitstorten, individuelle Desserts und festliche Candy Bars. Wir arbeiten mit persönlichen Wünschen, wählen eine stilvolle Präsentation und achten auf den perfekten Geschmack jedes Produkts. Alles wird mit Liebe und großer Sorgfalt in Kamjanez-Podilskyj hergestellt. Wenn Sie bei uns bestellen, erhalten Sie mehr als ein Dessert – Sie bekommen Emotion, Ästhetik und süßen Genuss auf höchstem Niveau.',
	'Web Art Work is the technology partner of PORTIER CAKE. We created a modern website so clients can conveniently browse the assortment, place orders, and get up-to-date information. We also configured a CRM system for order tracking and client communication and automated part of the business processes. Alongside technical support, we support the project in marketing. Our goal is to help the brand grow online as elegantly as its desserts look and taste.':
		'Web Art Work ist der Technologiepartner von PORTIER CAKE. Wir haben eine moderne Website geschaffen, damit Kunden das Sortiment bequem ansehen, Bestellungen aufgeben und aktuelle Informationen erhalten können. Außerdem haben wir ein CRM-System für Auftragsverfolgung und Kundenkommunikation eingerichtet und einen Teil der Geschäftsprozesse automatisiert. Neben dem technischen Support unterstützen wir das Projekt auch im Marketing. Unser Ziel ist es, der Marke dabei zu helfen, online so elegant zu wachsen, wie ihre Desserts aussehen und schmecken.',
	'UA Code is a mobile application for learning programming in Ukrainian. We created a convenient platform for people who want to learn programming from scratch using Ukrainian-language syntax and clear explanations. The app combines theory, practical tasks, and interactive examples. It also includes a study book for systematic learning. UA Code is a first step into IT for school students, university students, and everyone who wants to grow in the technology space without losing touch with their native language. Learn code in your own language and shape your own future.':
		'UA Code ist eine mobile Anwendung zum Erlernen von Programmierung auf Ukrainisch. Wir haben eine komfortable Plattform für Menschen geschaffen, die Programmieren von Grund auf lernen möchten – mit ukrainischer Syntax und klaren Erklärungen. Die App verbindet Theorie, praktische Aufgaben und interaktive Beispiele. Außerdem enthält sie ein Lernbuch für ein systematisches Studium. UA Code ist ein erster Schritt in die IT für Schüler, Studierende und alle, die im Technologiebereich wachsen möchten, ohne die Verbindung zur eigenen Muttersprache zu verlieren. Lerne Code in deiner eigenen Sprache und gestalte deine eigene Zukunft.',
	'Web Art Work is the technology partner of the educational project UA Code. We developed a mobile application for learning programming in Ukrainian and built the learning structure with interactive exercises, tests, and theory blocks. We delivered the full cycle from UI/UX design to development and marketplace publication. We also support the project in marketing, SEO, and branding. Our goal is to make digital education accessible, high-quality, and genuinely Ukrainian.':
		'Web Art Work ist der Technologiepartner des Bildungsprojekts UA Code. Wir haben eine mobile Anwendung zum Erlernen von Programmierung auf Ukrainisch entwickelt und die Lernstruktur mit interaktiven Übungen, Tests und Theorieblöcken aufgebaut. Wir haben den vollständigen Zyklus geliefert – von UI/UX-Design über Entwicklung bis zur Veröffentlichung in den Stores. Darüber hinaus unterstützen wir das Projekt in Marketing, SEO und Branding. Unser Ziel ist es, digitale Bildung zugänglich, hochwertig und wirklich ukrainisch zu machen.',
};
