export const students = [
	{
		_id: '65d48be1a7bfe5b3745472b1',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Arthur Hlushko',
		role: 'Full Stack Developer',
		grade: '100 / 100',
		activity: '100%',
		thumb: '/api/file/get/general/1708428208133.png?1708428208176',
		description:
			"Arthur Hlushko has distinguished himself as an exceptionally diligent and proficient developer throughout the recent practice session. His commitment to the projects was evident through his extensive contributions, particularly in fixing numerous bugs and enhancing the overall functionality and user experience of both web and mobile applications.\n\nArthur's active participation extended beyond his immediate tasks; he was highly communicative, consistently engaging with the team to share insights, offer solutions, and address any issues promptly and effectively. His approach to collaboration and problem-solving significantly contributed to a positive and productive work environment.\n\nThe quality of Arthur's coding is noteworthy. He has demonstrated a deep understanding of front-end development principles and applied best practices effectively across various projects. His work on the website's front-end and the mobile application was not only functional but also aesthetically pleasing, user-friendly, and optimized for performance.\n\nMoreover, Arthur's ability to balance speed with quality, manage his workload efficiently, and maintain high standards of coding has set a positive example for his peers. His proactive nature and willingness to take on challenges have made him a valuable asset to the team.\n\nGiven his outstanding performance, dedication to quality, and team spirit, I highly recommend Arthur Hlushko to any IT agency looking for a developer with a strong work ethic and excellent technical skills. Arthur's adaptability and proficiency in both web and mobile development make him an ideal candidate for diverse development projects.",
		url: 'arthurhlushko',
		inc: 1,
		email: null,
		location: 'Kamianets Podilskiy',
		phone: '+380969912498',
		salary: '2000$',
	},
	{
		_id: '65dee8ba21d360c9a1fa2d91',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Maksym Tarasov',
		inc: 2,
		role: 'Front End Developer',
		phone: '+380681307732',
		email: 'makstarasovv1@gmail.com',
		location: 'Chernivtsi',
		grade: '100 / 100',
		activity: '100%',
		thumb: '/api/file/get/general/1709107901588.png?1709107901663',
		description:
			"Maksym has shown exceptional dedication and skill in his contributions to the Waiter Cloud startup. His efforts in enhancing the website have significantly improved its functionality and user experience, which is a testament to his technical acumen and understanding of our customer's needs. His ability to not only address but also anticipate the requirements of the project has resulted in a more intuitive and user-friendly interface. His commitment to quality and attention to detail have been evident in every task he has undertaken.\n\nFurthermore, Maksym's development of two distinct themes for our customers showcases his creativity and versatility as a designer. These themes have not only enriched the visual appeal of our platform but have also provided our users with more personalized and engaging experiences. His work reflects a deep understanding of brand identity and user engagement, which are crucial elements in the competitive landscape of digital services. Maksym's ability to blend aesthetics with functionality has greatly contributed to enhancing the overall value of our offerings.\n\nOn top of his technical and creative contributions, Maksym has been an exemplary team member. His active and communicative approach has fostered a positive and collaborative environment within our team. He is always ready to lend a hand or share his insights, which has greatly enhanced the efficiency and morale of our team. Maksym's proactive nature and willingness to go above and beyond have been instrumental in driving our project forward. His enthusiasm and dedication are truly commendable, and he is undoubtedly a valuable asset to the Waiter Cloud startup.",
		url: 'maksymtarasov',
		salary: '1000$',
	},
	{
		_id: '65deeef721d360c9a1fa2dad',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Mykola Mozoliuk',
		inc: 3,
		role: 'Full Stack Developer',
		phone: '+380988599315',
		email: null,
		location: 'Kamianets Podilskiy',
		grade: '100 / 100',
		activity: '90%',
		thumb: '/api/file/get/general/1709548567076.png?1709548567160',
		description:
			'Throughout the recent practice session, Mykola Mozoliuk has shown exceptional commitment and proficiency in both front-end and back-end development. He has undertaken a variety of complex tasks, demonstrating not only a deep understanding of technical concepts but also the ability to apply them effectively in practical scenarios.\n\nOn the back-end side, Mykola has successfully tackled challenging programming tasks that required advanced knowledge and skill. His work included developing robust server-side functionalities, optimizing database interactions, and ensuring the security and efficiency of web services. His contributions have been integral to the stability and performance of our projects.\n\nIn front-end development, Mykola has excelled in creating dynamic, responsive, and user-friendly interfaces. He has demonstrated a strong grasp of JavaScript and various scripting frameworks, enabling him to implement complex features and enhance user interaction. His attention to detail and commitment to quality have resulted in highly engaging and accessible web applications.\n\nFurthermore, Mykola has shown remarkable progress and a keen interest in improving his skills throughout the practice period. He has been proactive in addressing critical tasks, often going above and beyond the requirements to deliver solutions of the highest standard.\n\nGiven his outstanding performance, dedication, and continuous self-improvement, I highly recommend Mykola Mozoliuk to any IT agency seeking a high-quality developer. His technical abilities, combined with his problem-solving mindset and work ethic, make him an invaluable asset to any team.',
		url: 'mykolamozoliuk',
		salary: '2000$',
	},
	{
		_id: '65deef0f21d360c9a1fa2db0',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Bohdan Prodoliak',
		inc: 4,
		role: 'Front End Developer',
		phone: '+380636671780',
		email: null,
		location: 'Kamianets Podilskiy',
		grade: '50 / 100',
		activity: '50%',
		thumb: '/api/file/get/general/1709548181821.png?1709548181859',
		description:
			"During the recent practice session, Bohdan Prodoliak was tasked with developing a website theme tailored for a restaurant. This assignment aimed to cultivate his skills in web development, focusing primarily on HTML and CSS, the foundational technologies for creating web pages.\n\nBohdan's involvement in this project resulted in the creation of several web pages intended to showcase the restaurant's brand, menu, and location. While the work completed did not cover an extensive range of functionalities or pages, it provided Bohdan with a platform to apply basic web development principles and techniques.\n\nIn the process, he demonstrated an understanding of HTML by structuring the website's content effectively and employing various HTML tags to define text, links, images, and other content types. Additionally, Bohdan utilized CSS to enhance the visual appeal of the website, applying styles to improve layout, color schemes, and font choices, contributing to a more engaging user experience.\n\nDespite the limited scope of his contributions, this practice offered Bohdan an opportunity to familiarize himself with the essentials of web design and development. Moving forward, it is recommended that Bohdan expands his efforts by incorporating more advanced features and functionalities, such as responsive design, user interaction, and form handling, to further develop his skills and understanding of web development.\n\nOverall, while Bohdan's work during this period was modest, it laid the groundwork for future learning and improvement in the field of web development.",
		url: 'bohdanprodoliak',
		salary: '300$',
	},
	{
		_id: '65deef1e21d360c9a1fa2db3',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Oleksandr Humeniuk',
		inc: 5,
		role: 'Front End Developer',
		phone: '+380680761441',
		email: null,
		location: 'Kamianets Podilskiy',
		grade: '60 / 100',
		activity: '50%',
		thumb: '/api/file/get/general/1709550205467.png?1709550205510',
		description:
			"During the recent practice session, Oleksandr Humeniuk contributed to the development of a website theme aimed at the restaurant industry. His involvement, while not extensive, provided him with foundational exposure to web development, particularly in the realms of HTML, CSS, and basic scripting.\n\nOleksandr's commitment to the project was moderate; he was partly available due to other commitments but managed to contribute within his capacity. His work on the restaurant theme, although not fully completed, showcased his initial understanding and application of web design principles. This project served as an introduction to the complexities of web development and highlighted the importance of time management and consistent effort in project completion.\n\nIn scripting, Oleksandr tried to engage with basic programming concepts. Although at the very beginning of his journey in scripting, he showed interest and made an effort to understand and apply basic JavaScript, which is commendable as a starting point. This initial step into scripting is crucial for his growth in web development and indicates a willingness to learn and expand his skill set.\n\nOverall, Oleksandr's performance was average, reflecting his current stage of learning and availability. He demonstrated a basic understanding and effort in the tasks he undertook. Moving forward, it is recommended that Oleksandr continues to build upon his foundational knowledge, focusing on completing projects and deepening his understanding of both front-end and back-end development to enhance his skills and effectiveness as a developer.",
		url: 'oleksandrhumeniuk',
		salary: '400$',
	},
	{
		_id: '65deef2a21d360c9a1fa2db6',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Denys Khorolsky',
		inc: 6,
		role: 'Front End Developer',
		phone: '+380683421626',
		email: null,
		location: 'Kamianets Podilskiy',
		grade: '20 / 100',
		activity: '20%',
		thumb: '/api/file/get/general/1709550488139.png?1709550488145',
		description:
			"During the recent practice session, Denys Khorolsky was assigned the task of contributing to the development of a website theme designed for the restaurant industry. Unfortunately, Denys exhibited very low activity throughout the project duration and displayed minimal communication with team members and mentors.\n\nDenys's involvement in the development process was significantly limited. He was unable to complete the assigned theme for the restaurant, and his contributions were minimal. This lack of activity has made it challenging to accurately assess his skills and understanding in web development areas such as HTML, CSS, and client-side scripting.\n\nDespite the expectations set at the beginning of the practice session, Denys did not engage actively with the project or seek assistance to overcome challenges. This resulted in a lack of substantive work to review and evaluate.\n\nMoving forward, it is crucial for Denys to address these issues by increasing his engagement and communication within the team. Active participation and consistent effort are essential for personal and professional development, especially in the dynamic field of web development.\n\nIn future projects, it would be beneficial for Denys to set clear goals, communicate more effectively with his peers and supervisors, and dedicate sufficient time to his assignments. By taking these steps, he can improve his performance and make the most of his learning opportunities.",
		url: 'denyskhorolsky',
		salary: '100$',
	},
	{
		_id: '65e1a9019a413d0567d0e9b9',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Denys Narolskyi',
		inc: 7,
		role: 'Full Stack Developer',
		phone: '+380982217420',
		email: 'denisnarolskyi@gmail.com',
		location: 'Kamianets Podilskyi',
		grade: '100 / 100',
		salary: '2000 $',
		activity: '100%',
		thumb: '/api/file/get/general/1709288270752.png?1709288270805',
		description:
			"Denys Narolskyi stands out as an exemplary figure due to his active participation and exceptional communication skills. Demonstrating a rare dedication, he invested additional time beyond the required hours, driven by genuine enthusiasm and a keen interest in his projects.\n\nWaiter Cloud (Food Industry):\nRole and Achievements: Denys played a pivotal role in the development of 'Waiter Cloud,' a forward-thinking startup aimed at revolutionizing the food industry. Displaying a versatile skill set, he contributed to both the back-end and front-end development, showcasing his ability to handle a comprehensive range of technical tasks. Furthermore, Denys exhibited creativity and practicality by designing a user-friendly template for restaurants, enhancing the overall customer experience and operational efficiency.\nSkills Demonstrated: Full-stack development, UI/UX design, problem-solving, project management.\n\nCar By World (Automotive Industry):\nRole and Achievements: Within the automotive sector, Denys significantly contributed to 'Car By World,' a startup addressing contemporary challenges in the car industry. He were instrumental in solving critical bugs and implementing two new features, which significantly improved the platform's functionality and user satisfaction. Moreover, Denys provided invaluable support to other developers, aiding in the resolution of his issues and facilitating a collaborative and productive work environment.\nSkills Demonstrated: Backend development, feature implementation, collaborative teamwork, debugging.\n\nEwawka (Medical Industry):\nRole and Achievements: In the medical startup 'Ewawka,' Denys continued to exhibit his strong problem-solving skills and technical prowess. He were responsible for fixing persistent bugs and adding an innovative feature that enhanced the platform's service quality. Additionally, Denys played a mentorship role, assisting fellow developers with his tasks and ensuring timely and effective solutions to client-related issues.\nSkills Demonstrated: Problem-solving, feature development, mentorship, client service.\n\nConclusion:\nDenys Narolskyi proactive approach, combined with his willingness to exceed expectations and contribute substantial time and effort, underscores his dedication and potential in the field of technology and entrepreneurship. his ability to adapt to different environments, coupled with his skills in coding, debugging, and teamwork, makes them a valuable asset to any project or organization.",
		url: 'denysnarolskyi',
	},
	{
		_id: '67be01a4f9b9e866a1462485',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Victor Kniahnytskyi',
		inc: 8,
		role: 'Front-end Developer',
		phone: '+380677821514',
		email: 'vcutler02@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '70 / 100',
		salary: '1500$',
		activity: '60%',
		thumb: '/api/file/get/general/1741005321077.png?1741005321105',
		description:
			'Victor Kniahnytskyi demonstrated a solid effort throughout the practice session, working on the wCar mobile application. While his overall performance was average, he remained active and engaged, consistently seeking guidance and asking questions to improve his work.\n\nHis willingness to communicate and clarify requirements was a positive aspect, ensuring that he stayed on track and addressed potential issues early. He successfully contributed to the development of both the Android and iOS versions of the application, implementing key features and maintaining steady progress.\n\nAlthough some areas could have benefited from more independent problem-solving, Victor showed a strong willingness to learn and adapt. With further experience and a more proactive approach to technical challenges, he has the potential to grow into a highly capable developer.\n\nOverall, Victor’s contributions were reliable, and his engagement with the team helped create a collaborative environment. With continued practice and deeper technical refinement, he can further enhance his skills and efficiency in future projects.',
		url: 'victorkniahnytskyi',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be01b6f9b9e866a146248b',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Dmytro Andronik',
		inc: 9,
		role: 'Front-end Developer',
		phone: '+380968621279',
		email: 'andronikdima3@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '35 / 100',
		salary: '500$',
		activity: '20',
		thumb: '/api/file/get/general/1741005027275.png?1741005027285',
		description:
			'Dmytro Andronik worked on the wFun mobile application, delivering a functional implementation. While his contributions were steady, his lack of enthusiasm was noticeable, which at times affected his engagement with the team and the overall project.\n\nDespite this, Dmytro managed to complete his assigned tasks, implementing core features for both Android and iOS. His technical approach was adequate, and he followed the necessary development processes, but there was room for a more proactive mindset in problem-solving and improving the application beyond basic requirements.\n\nOverall, Dmytro did a decent job, and with more initiative, he could further develop his technical skills and make a stronger contribution to the team.',
		url: 'dmytroandronik',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be01d3f9b9e866a146248e',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Max Sas',
		inc: 10,
		role: 'Front-end Developer',
		phone: '+380972325497',
		email: 'maksimsas12@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '100 / 100',
		salary: '2000$',
		activity: '100%',
		thumb: '/api/file/get/general/1740578392202.png?1740581040844',
		description:
			"Max Sas has shown exceptional dedication and technical ingenuity throughout the practice session, consistently exceeding expectations. His ability to find creative and effective solutions to complex problems was a key strength, making a significant impact on the development process.  \n\nA standout achievement was his work on the wHealth (Health Care) app, where he demonstrated a deep understanding of both functionality and user experience. His problem-solving skills were evident as he tackled challenges efficiently, ensuring a smooth and optimized final product.  \n\nMax's proactive and open-minded approach made him highly adaptable to feedback and improvements. He was always willing to refine features, explore alternative solutions, and implement enhancements that elevated the overall quality of the application. His enthusiasm for innovation and commitment to excellence were clear throughout the project.  \n\nBeyond his technical expertise, Max's engagement with the team was outstanding. His strong communication skills and collaborative nature helped create a dynamic and productive work environment. His ability to think critically and implement well-structured solutions made him a key contributor to the team's success.  \n\nGiven his outstanding problem-solving ability, technical excellence, and proactive mindset, I highly recommend Max Sas for any IT role. His innovative approach, adaptability, and commitment to delivering high-quality software make him a valuable asset to any development team.",
		url: 'maxsas',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be01f2f9b9e866a1462494',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Oleksandr Mrachkovsky',
		inc: 11,
		role: 'Front-end Developer',
		phone: '+380665714514',
		email: 'oleksandrmrackovskij71@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '100 / 100',
		salary: '2000$',
		activity: '100%',
		thumb: '/api/file/get/general/1740577721917.png?1740577721925',
		description:
			"Oleksandr Mrachkovsky demonstrated exceptional dedication and technical expertise throughout the practice session, consistently exceeding expectations. His proactive approach and ability to deliver high-quality solutions made him a key contributor to the team's success.  \n\nOne of his standout achievements was the development of the wPet (Veterinary Care) application, which he successfully built for both Android and iOS. His attention to detail and commitment to delivering an outstanding user experience ensured that the app met the highest standards. Oleksandr not only implemented the core functionality efficiently but also introduced enhancements that improved usability and performance.  \n\nHe is open to new ideas and adapts easily to feedback, allowing him to refine the product quickly. Oleksandr actively sought opportunities to improve the application, demonstrating strong problem-solving skills and a willingness to implement innovative solutions.  \n\nBeyond his technical achievements, his energy and positive attitude had a great impact on the entire team. His strong communication skills, teamwork, and solution-oriented mindset made him a reliable and highly effective team member.  \n\nGiven his outstanding performance, technical skills, and proactive approach, I highly recommend Oleksandr Mrachkovsky for any IT role. His ability to take ownership of projects, refine solutions, and consistently deliver top-tier results makes him a valuable asset to any development team.",
		url: 'oleksandrmrachkovsky',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be0202f9b9e866a1462497',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Pavlo Izhytskyi',
		inc: 12,
		role: 'DevOps',
		phone: '+380934102802',
		email: 'izhytskyi@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '80 / 100',
		salary: '1500$',
		activity: '60%',
		thumb: '/api/file/get/general/1740578933207.png?1740581825798',
		description:
			'Pavlo Izhytskyi played a crucial role in the practice session, focusing on DevOps for the wTask mobile application. His expertise in infrastructure and system integration ensured a smooth and scalable development process, making a significant impact on the project’s overall functionality.\n\nA standout achievement was his setup and integration of DeepSeek, Coqui, and Whisper LMs, seamlessly connecting them with our API and effectively handling requests. His deep technical understanding and problem-solving skills were evident as he worked through complex configurations and optimizations.\n\nBeyond implementation, Pavlo took a structured and methodical approach, documenting every aspect of his work in detail. His thorough documentation ensures long-term maintainability, making it easier for future developers to build upon his contributions.\n\nHis ability to bridge development and operations was impressive, demonstrating strong DevOps principles, automation skills, and a deep understanding of both software and infrastructure. His proactive nature and dedication to quality made him a key asset to the team.\n\nGiven his outstanding work in system architecture, API integration, and documentation, I highly recommend Pavlo Izhytskyi for any DevOps or backend infrastructure role. His ability to handle complex integrations and ensure system stability makes him a valuable addition to any tech team.',
		url: 'pavloizhytskyi',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be021ef9b9e866a146249d',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Ruslan Yaremko',
		inc: 13,
		role: 'Front-end Developer',
		phone: '+380987573317',
		email: 'yaremkoruslan69@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '60 / 100',
		salary: '1200$',
		activity: '50%',
		thumb: '/api/file/get/general/1741005064737.png?1741005064745',
		description:
			"Ruslan Yaremko delivered a solid performance throughout the practice session, showing consistent effort and engagement in his work. While his results were okay overall, his active participation and willingness to stay involved in discussions made a positive impact on the team.  \n\nHe approached tasks responsibly, ensuring that assigned features were implemented properly. His engagement and communication skills were strong, as he frequently interacted with the team, asked relevant questions, and contributed to problem-solving efforts. A key achievement was his work on the wBody application, where he played an important role in its development and ensured steady progress.  \n\nAlthough there is room for deeper technical refinement and more independent initiative, Ruslan's active approach and steady performance indicate good potential for growth. With further experience and refinement of his skills, he can become a more confident and efficient developer.  \n\nOverall, Ruslan was a reliable team member, contributing effectively and maintaining an active presence in the project. His commitment to learning and collaboration will serve him well in future development roles.",
		url: 'ruslanyaremko',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be022cf9b9e866a14624a3',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Roman Stolyar',
		inc: 14,
		role: 'Front-end Developer',
		phone: '+380971176218',
		email: 'roman.stoliar@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '80 / 100',
		salary: '1500$',
		activity: '75%',
		thumb: '/api/file/get/general/1740578747104.png?1740578747111',
		description:
			'Roman Stolyar has shown steady dedication and perseverance throughout the practice session. While he was less active than some of his peers, his commitment to delivering quality work was evident, and he consistently put in the effort to complete his tasks to the best of his ability.  \n\nA key achievement was his work on the wProperty mobile application, successfully developing it for both iOS and Android. Despite challenges, he managed to implement core functionalities effectively, ensuring the app met the expected requirements. His structured approach and focus on delivering a functional product contributed to the overall success of the project.  \n\nRoman demonstrated a willingness to learn and improve, carefully addressing feedback and refining his work when needed. While there were areas where he could have been more proactive, his persistence and ability to complete tasks reliably made a positive impact on the project.  \n\nOverall, Roman did a solid job and showed potential for further growth. With continued practice and a more engaged approach, he has the capability to develop into a strong and effective developer.',
		url: 'romanstolyar',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '67be023af9b9e866a14624a6',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Yurii Stefura',
		inc: 15,
		role: 'Front-end Developer',
		phone: '+380979100524',
		email: 'yurastefura7@gmail.com',
		location: 'Kamianets Podilskiy',
		grade: '70 / 100',
		salary: '1300$',
		activity: '60%',
		thumb: '/api/file/get/general/1741005052036.png?1741005052043',
		description:
			'Yurii Stefura demonstrated strong activity and engagement throughout the practice session, making valuable contributions to the wFood mobile application. His proactive approach and willingness to stay involved in discussions helped drive the project forward.\n\nHe worked diligently to implement key features for both Android and iOS, ensuring the application met functional expectations. His enthusiasm for problem-solving and ability to quickly adapt to challenges were evident, making him a reliable and effective team member.\n\nYurii’s active communication and collaboration skills allowed him to efficiently address issues and improve the app’s overall quality. While there is always room for further technical refinement, his commitment to learning and improving his skills was clear throughout the project.\n\nOverall, Yurii performed well, showing initiative, responsibility, and strong teamwork. With continued development experience, he has the potential to become an even more capable and confident mobile developer.',
		url: 'yuriistefura',
		calendar: '20.01.2025 - 10.03.2025',
	},
	{
		_id: '6867bdb79191478c6d4a9195',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Nadiia Tverdokhlib',
		inc: 16,
		url: 'nadiiatverdokhlib',
		location: 'Kamianets-Podilskiy',
		description:
			'Nadiia Tverdokhlib demonstrated exceptional leadership, creativity, and technical skill throughout the practice period. As a key member of the team, she took ownership of the UaCode project — an educational application designed to teach programming using Ukrainian-language syntax — and successfully guided its development from concept to implementation.  Nadiia played a central role in coordinating team efforts, ensuring that each development stage met both educational and technical standards. Her structured approach and strong organizational skills enabled the project to progress efficiently and with clear vision. In addition to managing the application’s development, Nadiia also curated and maintained the project’s Instagram page, effectively engaging the target audience and promoting the unique value of learning programming in Ukrainian.  One of her most impactful contributions was the creation of a printed learning guide for UaCode, which complemented the app by offering structured, accessible materials for learners. This initiative showcased her ability to think beyond digital solutions and provide tangible educational tools that support a broader learning experience.  Nadiia’s adaptability, attention to detail, and communication skills made her a driving force within the team. She approached every challenge with enthusiasm and professionalism, actively seeking ways to improve both the technical and educational aspects of the product.  Given her diverse skill set, leadership qualities, and commitment to delivering meaningful, user-centered solutions, Nadiia Tverdokhlib is highly recommended for any IT or edtech role. Her ability to lead, create, and connect makes her an invaluable addition to any development or product team.',
		email: 'dome.hope.tv@gmail.com',
		phone: '+380988171559',
		salary: '1200$',
		activity: '95%',
		grade: '98 / 100',
	},
	{
		_id: '6867bf089191478c6d4a91f5',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Anastasia Mazur',
		inc: 17,
		location: 'Kamianets-Podilskiy',
		phone: '+380971517868',
		role: 'Front-end Developer',
		description:
			"Anastasia Mazur demonstrated outstanding professionalism, technical proficiency, and continuous initiative throughout the practice period, consistently showing a strong sense of responsibility and results-driven focus. Her contributions to the enhancement and refinement of the wProperty application (a real estate app) played a key role in improving its efficiency, stability, and user experience.  Anastasia worked diligently on optimizing existing features and expanding the app's capabilities for both Android and iOS platforms. Through her keen attention to detail and deep understanding of user needs, she successfully implemented improvements that significantly enhanced the interface and overall system performance. She skillfully combined technical knowledge with a creative approach, enabling the introduction of innovative solutions tailored to the real estate market.  One of Anastasia's key strengths is her openness to feedback and ability to respond quickly to challenges. She proved to be a proactive team member, eager to collaborate, share ideas, and maintain a strong team dynamic. Her communication skills, structured thinking, and focus on quality were instrumental in the successful development of the application during the practice.  Given her solid technical skills, responsible attitude, and drive for continuous improvement, Anastasia Mazur is highly recommended for any IT role. Her ability to enhance existing solutions, take initiative, and maintain a professional standard of collaboration makes her a valuable asset to any development team.",
		url: 'anastasiamazur',
		salary: '1000$',
		activity: '85%',
		grade: '92 / 100',
	},
	{
		_id: '6867bf159191478c6d4a91f8',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Bogdan Habaz',
		inc: 18,
		location: 'Kamianets Podilskiy',
		phone: '+380971508771',
		description:
			"Bogdan Habaz showed strong technical capabilities and a focused, solution-oriented mindset during his work on the wProperty project, where he contributed as a Unity developer. His role involved implementing interactive elements and enhancing the visual and functional components of the application using Unity technologies.  Bogdan took responsibility for developing key features that required 3D interaction and visualization, helping to make the real estate app more dynamic and user-friendly. His understanding of Unity’s tools and real-time rendering techniques allowed the team to explore innovative ways to present property-related content, adding depth and interactivity to the user experience.  Throughout the project, Bogdan demonstrated reliability, attention to detail, and a clear understanding of project requirements. He communicated effectively with other team members, ensured timely delivery of tasks, and was always open to feedback, quickly refining and improving his implementations based on team input.  His ability to combine technical knowledge with creativity made a significant impact on the project's overall quality. Bogdan’s contribution added an important visual layer to the application, supporting the goal of creating an engaging and informative product for users.  Given his proficiency with Unity, dedication to delivering high-quality results, and ability to work collaboratively, Bogdan Habaz is highly recommended for any role involving interactive application or game development. His work ethic and technical strength make him a valuable asset to any development team.",
		role: 'Unity developer',
		url: 'bogdanhabaz',
		salary: '1000$',
		activity: '80%',
		grade: '82 / 100',
	},
	{
		_id: '6867bf1e9191478c6d4a91fb',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Eugene Verbitsku',
		inc: 19,
		location: 'Kamianets Podilskiy',
		description:
			'Eugene Verbitsku contributed to the wProperty project as a Unity developer, focusing on the integration of interactive components within the application. His work involved developing several basic features using Unity to support the visual and user-interactive aspects of the real estate app.  While Eugene completed his assigned tasks and demonstrated a working knowledge of Unity, his overall involvement in the project was limited. The level of enthusiasm and initiative expected in a collaborative and fast-paced development environment was not always present. As a result, his contribution, while functional, remained within a narrow scope and did not significantly influence the broader progress or innovation of the application.  There is potential for Eugene to further grow as a developer by strengthening his engagement with the development process, seeking feedback actively, and taking a more proactive role in team collaboration. With greater involvement and commitment, he could expand both his technical competencies and his contribution to future projects.  With additional focus on self-motivation and team communication, Eugene Verbitsku may become a more effective member of future development teams.',
		role: 'Unity developer',
		url: 'eugeneverbitsku',
		salary: '600$',
		activity: '50%',
		grade: '50 / 100',
	},
	{
		_id: '6867bf279191478c6d4a91fe',
		moderators: ['63b9245ff9e925059d9ef676'],
		author: '63b9245ff9e925059d9ef676',
		name: 'Denys Yaholnyk',
		inc: 20,
		location: 'Kamianets Podilskiy',
		description:
			'Denys Yaholnyk participated in the development of the wProperty project as a Unity developer, contributing to the creation of interactive features aimed at enhancing the user experience. He was responsible for implementing basic visual components and ensuring their integration within the application’s interface.  Although Denys demonstrated familiarity with Unity tools and completed a portion of the assigned tasks, his overall engagement in the project was limited. The work lacked consistent initiative and deeper involvement, which are essential in a collaborative environment focused on innovation and high-quality outcomes. His contributions, while technically correct, remained at a foundational level and did not significantly impact the advancement of the application.  To grow as a developer, Denys would benefit from adopting a more proactive mindset, showing greater ownership of tasks, and engaging more actively with the team. Improving his responsiveness to feedback and his ability to work independently could help him strengthen both his technical and collaborative skills.  With a clearer focus on initiative and team integration, Denys Yaholnyk has the potential to make more meaningful contributions in future development projects.',
		role: 'Unity developer',
		url: 'denysyaholnyk',
		salary: '200$',
		activity: '20%',
		grade: '20 / 100',
	},
	{
		_id: '69bb0ae88572456b34be91be',
		inc: 21,
		name: 'Vadym Valtser',
		description:
			'Vadym Valtser showed outstanding performance during the practice period from 2 лютого to 13 березня 2026. He proved himself to be a highly reliable and talented front-end developer who handled tasks with confidence, precision, and strong attention to detail.\n\nThroughout the practice, Vadym made a significant contribution to front-end development, improving interfaces, refining user interactions, and helping raise the overall quality of the projects. His work was consistently clean, thoughtful, and aligned with modern development standards.\n\nVadym also stood out for his strong communication and team collaboration. He was active in discussions, quick to respond to feedback, and always ready to help move the work forward. His professional attitude and excellent technical skills made him a valuable part of the team.\n\nGiven his exceptional results, full engagement, and high-quality work, I highly recommend Vadym Valtser to any IT company seeking a strong front-end developer with excellent potential and a great work ethic.',
		thumb: 'https://whub.webart.work/assets/vadymvaltser.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'vadymvaltser',
	},
	{
		_id: '69bb0b0e8572456b34be91c8',
		inc: 22,
		name: 'Victor Okriak',
		description:
			'Victor Okriak completed the practice period from 2 лютого to 13 березня 2026 with outstanding success. He demonstrated a high level of technical skill in front-end development and approached every task with responsibility, focus, and genuine dedication.\n\nDuring the practice, Victor actively worked on improving interfaces, implementing front-end functionality, and helping create user-friendly, polished results across the assigned projects. His code quality was consistently strong, and he showed great attention to usability, structure, and visual detail.\n\nVictor was also an excellent team participant. He communicated clearly, collaborated effectively, and maintained a positive and productive attitude throughout the practice. His willingness to contribute and solve problems made a strong impact on the overall team workflow.\n\nBased on his performance, I can confidently recommend Victor Okriak as a front-end developer to any IT agency or development team. He has shown both strong technical ability and the right mindset for successful professional growth.',
		thumb: 'https://whub.webart.work/assets/victorokriak.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'victorokriak',
	},
	{
		_id: '69bb0b0e8572456b34be91cb',
		inc: 23,
		name: 'Maksym Horetskyi',
		description:
			'Maksym Horetskyi performed exceptionally well during the practice period from 2 лютого to 13 березня 2026. He showed himself as a motivated and highly capable front-end developer who consistently produced quality work and approached each task with professionalism.\n\nHis contribution to the projects included implementing interface improvements, refining front-end logic, and helping ensure that the applications were both functional and visually well-executed. Maksym demonstrated a solid understanding of front-end development and a strong ability to apply that knowledge effectively.\n\nHe also impressed the team with his reliability, responsiveness, and active participation in the development process. Maksym was easy to work with, open to feedback, and always focused on delivering the best possible result.\n\nI highly recommend Maksym Horetskyi as a front-end developer. His technical strengths, work ethic, and strong level of engagement make him an excellent candidate for professional work in the IT industry.',
		thumb: 'https://whub.webart.work/assets/maksymhoretskyi.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'maksymhoretskyi',
	},
	{
		_id: '69bb0b0e8572456b34be91ce',
		inc: 24,
		name: 'Dmytro Demchenko',
		description:
			'Dmytro Demchenko delivered excellent results during the practice period from 2 лютого to 13 березня 2026. He demonstrated strong front-end development skills, a sharp eye for interface quality, and a disciplined approach to completing tasks on time and at a high standard.\n\nHis contributions were important in building and polishing project features, improving layouts, fixing issues, and ensuring that the final user experience was smooth and well-structured. Dmytro worked confidently with front-end tasks and showed a clear understanding of modern development practices.\n\nIn addition to his technical ability, Dmytro maintained a very professional and proactive attitude. He communicated well with the team, adapted quickly to project needs, and consistently showed responsibility in every assignment he handled.\n\nI highly recommend Dmytro Demchenko as a front-end developer for future roles in the IT field. His dedication, quality of work, and strong engagement make him a very promising specialist.',
		thumb: 'https://whub.webart.work/assets/dmytrodemchenko.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'dmytrodemchenko',
	},
	{
		_id: '69bb0b0e8572456b34be91d1',
		inc: 25,
		name: 'Vladyslav Levchuk',
		description:
			'Vladyslav Levchuk showed excellent results during the practice period from 2 лютого to 13 березня 2026. He proved himself to be a skilled and dependable front-end developer who approached work seriously and consistently delivered high-quality outcomes.\n\nThroughout the practice, Vladyslav contributed greatly to the development of interfaces and front-end features, paying close attention to both technical correctness and overall user experience. His work reflected strong coding standards, good design awareness, and a practical understanding of project requirements.\n\nVladyslav was also highly engaged in teamwork. He communicated effectively, handled feedback maturely, and maintained a professional attitude in every part of the development process. His consistency and dedication helped strengthen the overall quality of the team’s work.\n\nI confidently recommend Vladyslav Levchuk to any company looking for a talented front-end developer. He demonstrated excellent potential, strong discipline, and the ability to make valuable contributions in real development environments.',
		thumb: 'https://whub.webart.work/assets/vladyslavlevchuk.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'vladyslavlevchuk',
	},
	{
		_id: '69bb0b0e8572456b34be91d4',
		inc: 26,
		name: 'Roman Shulepko',
		description:
			'Roman Shulepko completed the practice period from 2 лютого to 13 березня 2026 with excellent performance and full dedication. He demonstrated strong front-end development abilities and a very responsible attitude toward every task assigned to him.\n\nRoman made valuable contributions to project development by improving front-end components, refining interface behavior, and helping create polished and user-friendly solutions. His work was accurate, well-structured, and reflected a clear understanding of modern front-end principles.\n\nHe was also an active and reliable team member who communicated well, stayed engaged in the workflow, and handled challenges with a calm and productive mindset. Roman’s consistency and positive attitude made him an important part of the team during the practice.\n\nI highly recommend Roman Shulepko as a front-end developer for future professional opportunities. His technical competence, strong effort, and excellent teamwork skills make him a very promising specialist.',
		thumb: 'https://whub.webart.work/assets/romanshulepko.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'romanshulepko',
	},
	{
		_id: '69bb0b0e8572456b34be91d7',
		inc: 27,
		name: 'Valeriia Makush',
		description:
			'Valeriia Makush completed the practice period from 2 лютого to 13 березня 2026 with exceptional success. She proved herself to be a highly capable front-end developer who combined strong technical execution with creativity, responsibility, and excellent consistency.\n\nHer work during the practice included building and improving front-end interfaces, enhancing usability, and contributing to the overall quality and polish of the projects. Valeriia paid close attention to both functionality and visual presentation, producing results that were clean, efficient, and user-focused.\n\nValeriia also demonstrated excellent teamwork and communication skills. She was active, dependable, open to collaboration, and always approached her tasks with professionalism and dedication. Her positive attitude and high level of engagement made her an important and respected member of the team.\n\nI highly recommend Valeriia Makush as a front-end developer. Her strong results, full commitment, and professional approach make her an excellent candidate for future opportunities in the IT industry.',
		thumb: 'https://whub.webart.work/assets/valeriiamakush.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'valeriiamakush',
	},
	{
		_id: '69bb0b0e8572456b34be91da',
		inc: 28,
		name: 'Anatolii Humelnyk',
		description:
			'Anatolii Humelnyk demonstrated outstanding performance during the practice period from 2 лютого to 13 березня 2026. He stood out as a highly committed front-end developer with strong technical skills, excellent discipline, and a clear focus on quality.\n\nDuring the practice, Anatolii worked actively on front-end tasks, improving interface elements, supporting feature implementation, and contributing to the overall stability and usability of the projects. His work was thoughtful, consistent, and completed with strong attention to detail.\n\nBeyond his technical achievements, Anatolii showed excellent communication and collaboration skills. He participated actively in team processes, responded well to feedback, and maintained a very professional and constructive attitude throughout the entire practice period.\n\nI confidently recommend Anatolii Humelnyk as a front-end developer. His performance, dedication, and ability to deliver excellent results make him a strong candidate for future roles in software development.',
		thumb: 'https://whub.webart.work/assets/anatoliihumelnyk.png',
		grade: '100 / 100',
		salary: '1500$',
		activity: '100%',
		role: 'Front-end Developer',
		location: 'Kamianets Podilskiy',
		url: 'anatoliihumelnyk',
	},
	{
		_id: '69bb0b0e8572456b34be91dd',
		inc: 29,
		name: 'Andrii Danylchuk',
		description:
			'Andrii Danylchuk demonstrated exceptional performance during the practice period from 2 лютого to 13 березня 2026. He proved himself to be a highly skilled and versatile full-stack developer, confidently handling both front-end and back-end responsibilities while maintaining an excellent standard of quality throughout all assigned work.\n\nDuring the practice, Andrii made significant contributions across multiple areas of development, including interface implementation, application logic, bug fixing, and overall project improvement. He showed a strong understanding of the full development cycle and was able to deliver solutions that were not only technically correct, but also practical, maintainable, and user-focused.\n\nAndrii also stood out for his proactive attitude, strong communication, and ability to work effectively within the team. He consistently demonstrated responsibility, independence, and readiness to solve complex problems. His balanced skill set and professional mindset made him an especially valuable contributor throughout the practice.\n\nI highly recommend Andrii Danylchuk to any IT company looking for a strong full-stack developer. His technical range, dedication, and excellent work ethic make him an outstanding candidate for professional software development roles.',
		thumb: 'https://whub.webart.work/assets/andriidanylchuk.png',
		grade: '100 / 100',
		salary: '2000$',
		activity: '100%',
		role: 'Full-stack Developer',
		location: 'Kamianets Podilskiy',
		url: 'andriidanylchuk',
	},
];
